stages:
  - build
  #- deploy

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      variables:
        IMAGE_TAG: "latest"
    - if: $CI_COMMIT_BRANCH != "master"
      variables:
        IMAGE_TAG: $CI_COMMIT_BRANCH

build_image:
  stage: build
  image: data61/magda-builder-docker:latest
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY}/${IMAGENAME}:${IMAGE_TAG} -f Dockerfile .
    - docker push ${CI_REGISTRY}/${IMAGENAME}:${IMAGE_TAG}
    - docker image rm ${CI_REGISTRY}/${IMAGENAME}:${IMAGE_TAG}
  only:
    - master
    # - develop

# deploy-dev:
#   stage: deploy
#   only:
#     - master
#   environment: 
#     name: development
#     url: https://manitude-dev.piman-digital.com
#   script:
#     - chmod og= $ID_RSA
#     - apk update && apk add openssh-client
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_DEV_CONNECTION "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_DEV_CONNECTION "cd $BACK_PATH_DEV  && docker-compose pull && docker-compose up -d "


variables:
  IMAGENAME: 'bumblebee/bumblebee-front'
  DOCKER_DRIVER: overlay2